const fs = require('fs');
const path = require('path');
const projectRoot = process.argv[2];
if (!projectRoot) throw new Error('Falta projectRoot');
const packagePath = path.join(projectRoot, 'package.json');
const raw = fs.readFileSync(packagePath, 'utf8').replace(/^\uFEFF/, '');
const pkg = JSON.parse(raw);
pkg.version = '5.22.0';
fs.writeFileSync(packagePath, JSON.stringify(pkg, null, 2) + '\n', { encoding: 'utf8' });
console.log('package.json actualizado a 5.22.0');
